name: DAST-ZAP Full Scan

permissions:
  issues: write
  contents: read

on:
  schedule:
    # Run at 00:00 UTC every 15th day of the month
    - cron: '0 0 1,16 * *'
  workflow_dispatch:  # Allows you to manually trigger the scan too

jobs:
  dast_zap:
    name: DAST-ZAP Full Scan
    runs-on: ubuntu-latest

    steps:
      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'https://demo.testfire.net/login.jsp'
          # Ensure output format is JSON
          reportType: 'json'
          # Specify the location of the JSON report output
          reportFile: '/zap/wrk/zap_scan_report.json'

      - name: Check if ZAP report exists
        run: |
          if [ ! -f /zap/wrk/zap_scan_report.json ]; then
            echo "ZAP scan report not found!"
            exit 1
          fi
          echo "ZAP scan report found!"

      - name: Upload ZAP scan JSON report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: zap_scan_report_json  # Artifact name for the JSON report
          path: /zap/wrk/zap_scan_report.json  # Correct file path for the generated report
