name: DAST-ZAP Full Scan

permissions:
  issues: write
  contents: read
  
on:
  schedule:
    # Run at 00:00 UTC every 15th day of the month
    - cron: '0 0 1,16 * *'
  workflow_dispatch:  # Allows you to manually trigger the scan too

jobs:
  dast_zap:
    name: DAST-ZAP Full Scan
    runs-on: ubuntu-latest

    steps:
      - name: Run ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.7.0
        with:
          target: 'https://demo.testfire.net/login.jsp'
