name: DAST-ZAP Full Scan

permissions:
  issues: write
  contents: read

on:
  schedule:
    # Run at 00:00 UTC every 15th day of the month
    - cron: '0 0 1,16 * *'
  workflow_dispatch:  # Allows you to manually trigger the scan too

jobs:
  dast_zap:
    name: DAST-ZAP Full Scan
    runs-on: ubuntu-latest

    steps:
      - name: Install ZAP and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-11-jdk
          # Download ZAP
          curl -sS https://github.com/zaproxy/zaproxy/releases/download/v2.11.1/ZAP_2.11.1_Unix.tar.gz -o zap.tar.gz
          # Verify the file was downloaded correctly
          ls -lh zap.tar.gz
          # Extract the archive
          tar -xvf zap.tar.gz
          # Check if the folder is extracted correctly
          ls -lh
          sudo mv zap-2.11.1 /opt/zap
          sudo ln -s /opt/zap/zap.sh /usr/local/bin/zap

      - name: Run ZAP Full Scan and print result in console
        run: |
          zap -cmd -quickurl 'https://demo.testfire.net/login.jsp' -quickout /dev/stdout -json
